dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/Gron44/otus-homeworks/2020-11/run.sh | bash
notifications:
  slack:
    secure: LRINXD1f539x62hbCw/jMTEhtv5ZgUSLY8+kXEN/T43BOeQpxbwNp0IwT9lRsTx4KRd8lMQ7rJIr7o9237wb0vwh12GHTq2A9r7LB7AaTugVgD5hvlFhtA/yy+T7ME0pc23ffOJmLIFewymUD6sbhsrzD0qJpnIGFrmtN2TIMLUQjwP83rohNvccJAU2URRnjMZC0bAOyD0RxytjFJ+m9BPwtKmoFE+7x4VSUWq4xcBip0mQ9sO8jpgjoUFU4S+2hyt5hUeEsZ3p6g7sH1vSblHQJZVO/5y870E3KoEHON8yjbsFb4w5aIggx1xauw7PWRGal7O21po2g0Aj56cp/ponUp3FZyO+1uXnP2zUaJxsIX2MtTO1cPgnMmiPhVJwl4sdtq/D3Ir/QhXxLg7777BRzxJGGRzG7fo84a6eDlaSr2WG/2hInEtVsUOxBsrSrs9Dj3kVZ57POhUnmU7YN3sELcxPzibet6qUKQhF1oUO/yxrk7zBKTqUd/TOL0NKt63Hg5f6GmA2yp7HTSQHS+/FxY1eMHbpqRGfb5oYfVxtXY6VMmlbbLp/j8/M2yYLEVEx3saz/Bdv3mcPOlnBnKEddtQLOumZ2eKtECg1ZrsfRpu2ZEDZWkme2/cDJzSe2JaE8lLRYaVwdYbBp6ea3fTlL1YcBFApXWzgu2dZJv8=
